### ISSUE TITLE
Consider refactoring NiLabel class

### ISSUE THREAD

**Issue by dzhoshkun** [SebastianoF/LabelsManager#4]
It's currently part of `nilabel.main`. Consider making it importable from `nilabel` directly. You may want to rename it as well, as currently it has the same name as the package itself. Maybe something like `App`.

Also, this class exposes the underlying "worker" objects, which goes against the rationale of the [command design pattern](https://github.com/SebastianoF/nilabel/wiki/Design-Pattern):

> Command decouples the object that invokes the operation from the one that knows how to perform it. 

 For instance to relabel, a call to `nil.manipulate.relabel()` is necessary, which means the caller needs to know the `LabelsManipulate` class interface. Instead, the "main" class should provide a `relabel()` method, which calls `LabelsManipulate.relabel()` (or any other implementation, should the implementation change in the future).

I would also recommend refraining from using short identifiers like `NiL` or `nil` (the second being more "dangerous"). Short identifiers are catchy, however prone to introducing compatibility issues, see for instance [one of the problems created by the new `async` keyword introduced as part of Python 3.7](https://github.com/tomerfiliba/rpyc/issues/253)

**Comment by SebastianoF** [comment]
Design pattern is an open question. Giving up the facade would mean having too many uncategorised options. At the moment the applications are collected under agents (or worker) and the tool is accessible according to their semantic. They are intended to work as drawers where you may the required tools. 

e.g. to get to the relabel, you type:
```
nil.manipulate.relabel(...
```
To get a segmentation with Otsu you will do:
```
nil.segment.otsu_thresholding(...
```
And the classes `LabelsManipulate ` and `LabelsSegmenter` are hidden from the user, that does not need to remember their names. If the user know what she wants and how to use auto-completion, she should be able to reach the right app, or to know that the app is not there yet.

I was afraid that allowing for direct call (`nil.otsu_thresholding` or `nil.relabel`) would remove the categorisation and would make reaching a method with auto-completion more lenghty.

Could be even better if you could do:
```
import nilabel as nil

nil.segment.otsu_thresholding(...)
```

Instead of 
```
from nilabel.main import Nilabel as NiL

nil = NiL()
nil.segment.otsu_thresholding(...)
```

But this I guess has to do with the import method (and the `__init__.py` in the main root) rather than the class architecture.

So the current choice I made is not the best one. The issue remains open, as refactoring class is well considered, after better importing system.

**Comment by SebastianoF** [comment]
Currently `main` is deprecated for `agents.AgentsController` and it works like:
```
import nilabels as nis

nis_app = nis.App('optiona_input_data_folder', 'optional_output_data_folder')
nis_app.manipulate.relabel('in_data_or_full_path.nii.gz', ...)
```
With `nis.<tab>` you can access `tools` (acting on numpy arrays or nibabel images),  `agents` (facade of tools acting on paths), and `App` (facade of facade agents).

Still considering more intuitive names than `agents` or `App`. Any idea?

**Comment by dzhoshkun** [comment]
Are you using the command design pattern as [mentioned here](https://github.com/SebastianoF/nilabels/wiki/Design-Pattern) or the facade design pattern?

**Comment by SebastianoF** [comment]
Facade. Documentation updated, thanks!
